// This file is generated by scripts/generate-people.mjs before each build.
export const generatedPeople = [
  {
    "name": "Anthony K. C. Tan",
    "role": "Principal Investigator",
    "image": "/images/people/anthony-tan.jpg",
    "alt": "Portrait of Anthony K. C. Tan",
    "email": "tan.anthony@nus.edu.sg"
  }
] as const;
