import { copyFile, mkdir, readdir, writeFile } from "node:fs/promises";
import path from "node:path";

const projectRoot = process.cwd();
const sourceDirectory = path.join(projectRoot, "people");
const publicDirectory = path.join(projectRoot, "public", "images", "people");
const outputFile = path.join(projectRoot, "content", "people.generated.ts");

const roleDetails = {
  PI: { label: "Principal Investigator", order: 0 },
  PD: { label: "Postdoctoral Researcher", order: 1 },
  RE: { label: "Research Engineer", order: 2 },
  PHD: { label: "PhD Student", order: 3 },
  UG: { label: "Undergraduate", order: 4 },
};

const filenamePattern = /^(PI|PHD|UG|RE|PD)_(.+)\.(png|jpe?g)$/i;

async function imageFiles(directory) {
  try {
    const entries = await readdir(directory, { withFileTypes: true });
    return entries.filter((entry) => entry.isFile() && filenamePattern.test(entry.name)).map((entry) => entry.name);
  } catch (error) {
    if (error?.code === "ENOENT") return [];
    throw error;
  }
}

function displayName(rawName) {
  const spacedName = rawName.replace(/_+/g, " ").replace(/\s+/g, " ").trim();
  const titleCased = spacedName
    .split(" ")
    .map((word) => (word ? `${word[0].toUpperCase()}${word.slice(1)}` : word))
    .join(" ");

  if (/^Anthony K C Tan$/i.test(titleCased)) return "Anthony K. C. Tan";
  return titleCased;
}

function personFromFilename(filename) {
  const match = filename.match(filenamePattern);
  if (!match) return null;

  const prefix = match[1].toUpperCase();
  const name = displayName(match[2]);
  const person = {
    name,
    role: roleDetails[prefix].label,
    image: `/images/people/${filename}`,
    alt: `Portrait of ${name}`,
    order: roleDetails[prefix].order,
  };

  if (prefix === "PI" && name === "Anthony K. C. Tan") {
    person.email = "tan.anthony@nus.edu.sg";
  }

  return person;
}

await mkdir(publicDirectory, { recursive: true });

const publicFiles = await imageFiles(publicDirectory);
const sourceFiles = await imageFiles(sourceDirectory);

for (const filename of sourceFiles) {
  await copyFile(path.join(sourceDirectory, filename), path.join(publicDirectory, filename));
}

const filenames = [...new Map([...publicFiles, ...sourceFiles].map((filename) => [filename.toLowerCase(), filename])).values()];
const discoveredPeople = filenames
  .map(personFromFilename)
  .filter(Boolean)
  .sort((left, right) => left.order - right.order || left.name.localeCompare(right.name));

if (!discoveredPeople.some((person) => person.role === "Principal Investigator")) {
  discoveredPeople.unshift({
    name: "Anthony K. C. Tan",
    role: "Principal Investigator",
    image: "/images/people/anthony-tan.jpg",
    alt: "Portrait of Anthony K. C. Tan",
    email: "tan.anthony@nus.edu.sg",
    order: 0,
  });
}

const peopleForSite = discoveredPeople.map(({ order: _order, ...person }) => person);
const fileContents = `// This file is generated by scripts/generate-people.mjs before each build.\nexport const generatedPeople = ${JSON.stringify(peopleForSite, null, 2)} as const;\n`;

await writeFile(outputFile, fileContents, "utf8");
console.log(`Generated ${peopleForSite.length} people profile${peopleForSite.length === 1 ? "" : "s"}.`);
